spring:
  application:
    name: images-service
  data:
    mongodb:
      database: images
      host: global-mongodb
      port: 27017
  cache:
    type: redis
    redis:
      host: redis-global
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8071

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
