spring:
  application:
    name: seller-service

  datasource:
    username: dripifyadmin
    password: dripifysuper123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://seller-postgres:5432/seller

  flyway:
    url: jdbc:postgresql://seller-postgres:5432/seller
    user: dripifyadmin
    password: dripifysuper123
    locations: classpath:db/migration
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/dripify

  cache:
    type: redis
    redis:
      host: redis-global
      port: 6379

server:
  port: 8073

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
